# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-18.04

variables:
- group: PermisosServer

steps:
- script: |
   sudo apt-get update -y
   sudo apt-get install default-jre -y
   sudo apt-get install openssh-server -y
  displayName: 'Instalando Dependencias'

- script:  |
   git clone https://github.com/josesolanor/Proyecto-gcs.git
   cd Proyecto-gcs
   sbt compile
   sbt test
  displayName: 'Fase de Verificacion de Contribucion'

- script:  |
   sudo systemctl start docker
   sudo docker run -d -e POSTGRES_PASSWORD=gcs -e POSTGRES_USER=gcs -e POSTGRES_DB=gcs -p 127.0.0.1:5432:5432 postgres:9.5
   export PGPASSWORD='gcs'
   until psql -h "127.0.0.1" -U "gcs" -c '\l'; do
   >&2 echo "Database no esta lista - esperando..."
   sleep 1
   done
   >&2 echo "Database lista! ;)"
   sbt "project gcsAppIT" test
  displayName: 'Fase de Verificacion de Pruebas de Integracion'

- task: DownloadSecureFile@1
  name: AppServerKey
  displayName: "Descargar Llave Privada de Servidor de Aplicaciones"
  inputs:
   secureFile: "WebServer_key.pem"

- script:  |
   sbt rpm:packageBin
   sudo cp $(AppServerKey.secureFilePath) /home/vsts/ && sudo chmod 600 /home/vsts/WebServer_key.pem
   sudo scp -v -o StrictHostKeyChecking=no -i /home/vsts/WebServer_key.pem /home/vsts/work/1/s/gcs-app/target/rpm/RPMS/noarch/gcs-app-2.8.x-1.noarch.rpm $(username)@$(ipapp):/home/$(username)
   sudo ssh -o StrictHostKeyChecking=no -i /home/vsts/WebServer_key.pem $(username)@$(ipapp) sudo systemctl stop gcs-app.service
   sudo ssh -o StrictHostKeyChecking=no -i /home/vsts/WebServer_key.pem $(username)@$(ipapp) sudo rpm -e gcs-app-2.8.x-1.noarch
   sudo ssh -o StrictHostKeyChecking=no -i /home/vsts/WebServer_key.pem $(username)@$(ipapp) sudo systemctl daemon-reload
   sudo ssh -o StrictHostKeyChecking=no -i /home/vsts/WebServer_key.pem $(username)@$(ipapp) sudo rpm -i gcs-app-2.8.x-1.noarch.rpm
   sudo ssh -o StrictHostKeyChecking=no -i /home/vsts/WebServer_key.pem $(username)@$(ipapp) sudo chown -R gcs-app /usr/share/gcs-app/
   sudo ssh -o StrictHostKeyChecking=no -i /home/vsts/WebServer_key.pem $(username)@$(ipapp) sudo chgrp -R gcs-app /usr/share/gcs-app/
   sudo ssh -o StrictHostKeyChecking=no -i /home/vsts/WebServer_key.pem $(username)@$(ipapp) sudo chown gcs-app:gcs-app /etc/gcs-app/application.conf
   sudo ssh -o StrictHostKeyChecking=no -i /home/vsts/WebServer_key.pem $(username)@$(ipapp) sudo sed -i 's/localhost:5432/$(hostdb):5432/' /etc/gcs-app/application.conf
   sudo ssh -o StrictHostKeyChecking=no -i /home/vsts/WebServer_key.pem $(username)@$(ipapp) sudo sed -i 's/localhost:9000/$(ipapp)/' /etc/gcs-app/application.conf
   sudo ssh -o StrictHostKeyChecking=no -i /home/vsts/WebServer_key.pem $(username)@$(ipapp) sudo chown gcs-app:gcs-app /etc/gcs-app/application.conf
   sudo ssh -o StrictHostKeyChecking=no -i /home/vsts/WebServer_key.pem $(username)@$(ipapp) sudo chown gcs-app:gcs-app /var/log/gcs-app/gcs-app.log
   sudo ssh -o StrictHostKeyChecking=no -i /home/vsts/WebServer_key.pem $(username)@$(ipapp) sudo rm /usr/share/gcs-app/RUNNING_PID
   sudo ssh -o StrictHostKeyChecking=no -i /home/vsts/WebServer_key.pem $(username)@$(ipapp) sudo systemctl restart gcs-app.service
  displayName: 'Fase de Despliegue a servidor de pruebas'
